// <auto-generated />
using System;
using DernekTakipOtomasyon.DataAccessLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DernekTakipOtomasyon.Migrations
{
    [DbContext(typeof(DernekTakipEntities))]
    [Migration("20231216203642_mig_create_db")]
    partial class mig_create_db
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DernekTakipOtomasyon.Models.Aidat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("decimal(18,2)")
                        .HasMaxLength(11);

                    b.Property<DateTime>("OdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("UyeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UyeID");

                    b.ToTable("Aidat");
                });

            modelBuilder.Entity("DernekTakipOtomasyon.Models.Aylar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AyAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Aylar");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AyAdi = "OCAK",
                            Tutar = 100m
                        },
                        new
                        {
                            ID = 2,
                            AyAdi = "ŞUBAT",
                            Tutar = 200m
                        },
                        new
                        {
                            ID = 3,
                            AyAdi = "MART",
                            Tutar = 300m
                        },
                        new
                        {
                            ID = 4,
                            AyAdi = "NİSAN",
                            Tutar = 400m
                        },
                        new
                        {
                            ID = 5,
                            AyAdi = "MAYIS",
                            Tutar = 500m
                        },
                        new
                        {
                            ID = 6,
                            AyAdi = "HAZİRAN",
                            Tutar = 600m
                        },
                        new
                        {
                            ID = 7,
                            AyAdi = "TEMMUZ",
                            Tutar = 700m
                        },
                        new
                        {
                            ID = 8,
                            AyAdi = "AĞUSTOS",
                            Tutar = 800m
                        },
                        new
                        {
                            ID = 9,
                            AyAdi = "EYLÜL",
                            Tutar = 900m
                        },
                        new
                        {
                            ID = 10,
                            AyAdi = "EKİM",
                            Tutar = 1000m
                        },
                        new
                        {
                            ID = 11,
                            AyAdi = "KASIM",
                            Tutar = 1100m
                        },
                        new
                        {
                            ID = 12,
                            AyAdi = "ARALIK",
                            Tutar = 1200m
                        });
                });

            modelBuilder.Entity("DernekTakipOtomasyon.Models.Duyuru", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("YetkiliAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YetkiliID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("YetkiliID");

                    b.ToTable("Duyuru");
                });

            modelBuilder.Entity("DernekTakipOtomasyon.Models.Uye", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<string>("EMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KanGrubu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sehir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TC")
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.HasKey("ID");

                    b.ToTable("Uye");
                });

            modelBuilder.Entity("DernekTakipOtomasyon.Models.Yetkili", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KullaniciAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Yetkili");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            KullaniciAd = "admin",
                            Sifre = "000"
                        });
                });

            modelBuilder.Entity("DernekTakipOtomasyon.Models.iller", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("sehir")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("iller");
                });

            modelBuilder.Entity("DernekTakipOtomasyon.Models.Aidat", b =>
                {
                    b.HasOne("DernekTakipOtomasyon.Models.Uye", null)
                        .WithMany("Aidats")
                        .HasForeignKey("UyeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DernekTakipOtomasyon.Models.Duyuru", b =>
                {
                    b.HasOne("DernekTakipOtomasyon.Models.Yetkili", null)
                        .WithMany("Duyurus")
                        .HasForeignKey("YetkiliID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
